name: time_management_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.12.1
  injectable: ^0.4.0+1
  get_it: ^4.0.2
  cupertino_icons: ^0.1.3
  provider: ^4.2.0
  rxdart: ^0.24.1
  shared_preferences: ^0.5.8
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^0.4.1
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/localization/